name: image_tools
description: A Photographers Toolbox.
publish_to: 'none' # Remove this line if you intend to publish the package

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0' # Adjust SDK constraint as needed

dependencies:
  flutter:
    sdk: flutter

  # State Management
  provider: ^6.0.5 # Or flutter_riverpod

  # File System & Path
  file_picker: ^6.0.0 # Check for latest version
  path: ^1.8.3

  # Desktop Features
  desktop_drop: ^0.4.4 # Check for latest version
  window_manager: ^0.2.8

  # Image Processing
  image: ^4.0.17 # Check for latest version
  # libraw_dart_bindings: ^0.1.0 # Or the specific version you find/use. Might need manual setup.
  ffi: ^2.1.0

  # Concurrency
  isolate: ^2.1.1 # Usually included with Dart SDK, but good to specify

  # UI Helpers (Optional, but useful)
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  # Add assets
  assets:
    - assets/img/logo.png